### ISSUE TITLE
Comment traduire le terme/concept Store ?

### ISSUE THREAD

**Issue by MachinisteWeb** [vuejs-fr/vue-ssr-docs#6]
Le « Store » est décrit comme un « pattern » de « gestion d'état ». De ce que j'en est lu il stock les données, et les gères en gardant un historique de leur changement d'état.

L'idée, si on le traduit, c'est de trouvé un mot proche de son sens premier et proche se ce qu'il le fait. Actuellement nous allons garder Store mais y a t-il quelque chose de mieux ?

Pour donner un exemple, le concept de « Slot » n'a pas été traduit dans la documentation original, je pencherais pour la même chose ici faute de traduction « clair ».

Et vous ?

**Comment by mdartic** [comment]
Je suis de ton avis, gardons store pour l'instant.

Le store est un 'state container', un conteneur d'état. Et tu y rajoutes la notion d'historique.

Mais bon, dire à chaque fois 'conteneur d'état' me paraît lourd et peut-être non autant évocateur que store.

=> je vote pour garder store.
