### ISSUE TITLE
Doit on accorder le mot 'client' avec le mot 'application', ou tout autre mot féminin

### ISSUE THREAD

**Issue by mdartic** [vuejs-fr/vue-ssr-docs#7]
On se pose une question avec @Haeresis [ici](https://github.com/vuejs-fr/vue-ssr-docs/pull/5#discussion_r115760937) et [là](https://github.com/vuejs-fr/vue-ssr-docs/pull/5#discussion_r115761536).

La question est, quand on parle d'une application, d'un code, d'une logique, qui s'effectue côté client, doit on accorder le mot client, qui représente l'environnement, avec le mot adjacent ? 
Par exemple, 
* logique spécifique client ou logique spécifique cliente ?
* application client ou application cliente ?

Autres exemples, on ne dit pas application serveuse, ni application cliente-serveur.
Mais pourtant, ça ne me choque pas si je lis application cliente, ou partie cliente...

Les deux mon adjudant ?

**Comment by MachinisteWeb** [comment]
Bonne question. Pour moi les deux se disent comme le SEO qui normalement est la SEO. 

Je suis presque sur que chaque occurrences du mot est accordée sur fr.vuejs.org. J'irai regarder. En tout cas ça n'est pas génant de changer rétroactivement la doc initiale le cas échéant. Juste etre cohérent :) 

D'autres avis ? Je suis curieux d'avoir l'avis de @sylvainpolletvillard la dessus !

**Comment by sylvainpolletvillard** [comment]
logique spécifique client ou logique spécifique cliente ? 
==> logique spécifique *au* client

application client ou application cliente ?
==> application *du* client ou application *côté* client

Vous essayez d'utiliser client et serveur comme des adjectifs mais ce sont bien des noms: c'est le client et le serveur. Donc pas d'accord et le mot de liaison qui va bien.
